language: cpp

compiler:
    - gcc
    - clang

branches:
  only:
    - master
    - dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - cmake --build .
    - ctest --output-on-failure
