language: cpp

compiler:
    - gcc
    - clang

branches:
  only:
    - master
    - dev

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - phantomjs --webdriver=7777 --webdriver-loglevel=WARN &

script:
    - cmake --build .
    - ctest --output-on-failure
